### ISSUE TITLE
opinion: website

### ISSUE THREAD

**Issue by ximenesyuri** [f-utils/general#1]
I think it would be interesting to have a website for our project to put important information, as collaborators and documentation.

I was thinking in using an instance of [ximenesyuri/termyx](https://github.com/ximenesyuri/termyx) with an improved displaying system for the documentations.

What you think about that?

I would also like some opinion on the domain to be used. Here are some options:
1. `f-utils.com`
2. `f-utils.io`
3. `f-utils.dev`
4. `f-utils.org`
5. `futils.io`
6. `futils.dev`
7. `futils.org`

@rdvid

**Comment by rdvid** [comment]
@ximenesyuri I like the 7th option: `futils.org`. 
- `futils` as a domain (without dash or any special character) serve as an implicit reinforcement of the main goal, and core concept, of FP: simplicity.
- Since `.org` is mainly used by several development libraries websites i think that is a good pattern to follow as well :).

**Comment by ximenesyuri** [comment]
Thank you @rdvid. Good points. I will register the `futils.org`.

**Comment by ximenesyuri** [comment]
This is a test comment

**Comment by ximenesyuri** [comment]
This is a test

**Comment by ximenesyuri** [comment]
Today I registered the domain `futils.org`. Thus, I will close the issue. @rdvid  @glaucojrcarvalho
